Working on pipelines

diff --git a/.github/workflows/Build-Release-Pipeline.yml b/.github/workflows/Build-Release-Pipeline.yml
--- a/.github/workflows/Build-Release-Pipeline.yml
+++ b/.github/workflows/Build-Release-Pipeline.yml
@@ -41,7 +41,7 @@ jobs:
     - name: Stop Website
       run: |
         # Stop the IIS website
-        iisreset /stop "HouseBids Website"
+        iisreset /stop "HouseBids Website" || echo "Ignoring error and continuing..."
 
     - name: Prepare local folders
       run: |       
